<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jv_banners"
 *
 * Auto generated by Extension Builder 2019-10-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF["jv_banners"] = [
    'title' => 'Banner Guthaben',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Joerg Velletti',
    'author_email' => 'typo3@velletti.de',
    'state' => 'beta',
    'version' => '12.4.3',
    'constraints' => [
        'depends' => [
            'typo3' => '12.4.0-12.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
