<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jv_banners"
 *
 * Auto generated by Extension Builder 2019-10-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Banner Guthaben',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Joerg Velletti',
    'author_email' => 'typo3@velletti.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
